include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_function_declarations_over_variables: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
